### ISSUE TITLE
How should I use rewind in your example?

### ISSUE THREAD

**Issue by Richacinas** [PactCoffee/react-body-classname#2]
Hi there,

This library is just great, but it is causing a memory leak on our production website.

I was wondering... how should I use rewind to avoid it?

Could you please show me in your example?

Thanks a lot.

**Comment by iest** [comment]
You need to call it before you render your app out using `react-dom` or whatever.

Something like:

```javascript
import React from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import ReactBodyClassName from 'react-body-classname'
import MyApp from './someplace'

export default function contrivedServer(req, res) {
  const bodyClassNames = ReactBodyClassName.rewind()
  const html = renderToStaticMarkup(<MyApp/>)
  res.end(`
  <!DOCTYPE html>
  <html>
    <body class=${bodyClassnames}>
      ${html}
    </body>
  </html>
`)
}
```

I'd add it to the example but server-side-rendering with react ain't really a solved problem yet so don't think it needs extra explanation above what's already in the readme.

If you disagree, feel free to open a PR :)

**Comment by Richacinas** [comment]
Good explanation.

I've got to say that I ended up doing this and the problem got totally solved.

cheers!
