### ISSUE TITLE
React.createClass warning after upgrading to React 15.5

### ISSUE THREAD

**Issue by natenorberg** [PactCoffee/react-body-classname#3]
After upgrading to React 15.5, I'm seeing this warning:

```
Warning: A Component: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
```

Can this be updated to be a JavaScript class?

**Comment by iest** [comment]
PRs welcome 😉

When I have time I'll move it over to `React.Component`. This won't be an issue until react 16 anyhow.

**Comment by batusai513** [comment]
@iest #4

**Comment by iest** [comment]
Fixed in https://github.com/iest/react-body-classname/releases/tag/v1.1.1 thanks to @batusai513
